name: IC3BERG pipeline on tags
on:
  push:
    branches:
      - dev
      - main
jobs:
  Build-Image:
    runs-on: self-hosted
    if: 
    steps:
      - uses: actions/checkout@v4
      - name: "Building dev image"
        if: github.ref == 'refs/heads/dev'
        run: docker build --no-cache -t outlaw/ic3burk:latest .
      - name: "Building prod image"
        if: github.ref == 'refs/heads/main'
        run: docker build --no-cache -t outlaw/ic3berg:latest .
  
  Copy-dependencies:
    runs-on: self-hosted
    needs: Build-Image
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p /home/outlaw/IC3BERG/db/data
      - run: cp init.sql /home/outlaw/IC3BERG/db/init.sql

  Deploy-DB:
    runs-on: self-hosted
    needs: Copy-dependencies
    steps:
      - uses: actions/checkout@v4
      - run: COMPOSE_STACK_NAME=IC3BERG_DB POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} docker compose up -d
  
  Deploy-Bot:
    runs-on: self-hosted
    needs: Build-Image
    steps:
      - uses: actions/checkout@v4
      - name: "Stop IC3BURK bot"
        if: github.ref == 'refs/heads/dev'
        continue-on-error: true
        run: docker stop IC3BURK && docker rm IC3BURK
        id: stop-burk
      - name: "Deploy IC3BURK"
        if: (github.ref == 'refs/heads/dev') && (success() || steps.stop-burk.conclusion == 'failure')
        run: docker run --name IC3BURK -d -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_DEV }} -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -e BOT_PREFIX="!" --restart unless-stopped --network ic3berg outlaw/ic3burk:latest
      - name: "Stop IC3BERG bot"
        if: github.ref == 'refs/heads/main'
        continue-on-error: true
        run: docker stop IC3BERG && docker rm IC3BERG
        id: stop-berg
      - name: "Deploy IC3BERG"
        if: (github.ref == 'refs/heads/main') && (success() || steps.stop-berg.conclusion == 'failure')
        run: docker run --name IC3BERG -d -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -e BOT_PREFIX="_" -e  --restart unless-stopped --network ic3berg outlaw/ic3berg:latest