name: IC3BERG pipeline on tags
on:
  push:
    branches:
      - main
jobs:
  Build-Image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building IC3BERG docker image as latest"
      - run: docker build --no-cache --build-arg DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} -t outlaw/ic3berg:latest .
      # - run: echo "Tag IC3BERG docker image using version ${{ github.head.ref }}"
      # - run: docker tag outlaw/ic3berg:${{ github.head.ref }} .

  Deploy:
    runs-on: self-hosted
    needs: Build-Image
    steps:
      - uses: actions/checkout@v4
      - run: echo "Parsing mariadb secret in .env"
      - run: echo "MARIADB_PASSWORD="${{ secrets.MARIADB_PASSWORD }} >> .env
      - run: echo "Restart IC3BERG container's stack"
      - run: docker compose up -d